"""Write embedded_build_config.py from DNG_API_URL / DIAGNOSTIC_API_URL (secure builds)."""
from __future__ import annotations

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "embedded_build_config.py"


DEFAULT_API_URL = "https://virello-secure.onrender.com"


def main() -> int:
    url = (
        os.environ.get("DNG_API_URL", "").strip()
        or os.environ.get("DIAGNOSTIC_API_URL", "").strip()
    ).rstrip("/")
    if not url:
        allow_default = os.environ.get("DNG_ALLOW_DEFAULT_API", "").strip().lower() in (
            "1",
            "true",
            "yes",
        )
        if allow_default:
            url = DEFAULT_API_URL
            print(f"Warning: using default API URL {url} (set DNG_API_URL for production).")
        else:
            print(
                "Set DNG_API_URL (or DIAGNOSTIC_API_URL) before building the distributable EXE.\n"
                "Example: set DNG_API_URL=https://your-api.onrender.com\n"
                "Or: set DNG_ALLOW_DEFAULT_API=1 to bake in the dev default URL.",
                file=sys.stderr,
            )
            return 1

    OUT.write_text(
        "# AUTO-GENERATED by scripts/generate_build_config.py — do not commit.\n"
        f'API_URL = "{url}"\n'
        "BUILD_PROTECTED = True\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
