/** Common executor / cheat names reviewers search for with Ctrl+F or the in-page filter. */
export const EXECUTOR_SEARCH_TERMS = [
  "AWP",
  "Arceus",
  "Bunni",
  "ChocoSploit",
  "Codex",
  "Comet",
  "Cosmic",
  "Cryptonite",
  "Delta",
  "DX9WARE",
  "Electron",
  "Evon",
  "Fluxus",
  "Furk",
  "Hydrogen",
  "JJSploit",
  "Krnl",
  "Lumen",
  "MacSploit",
  "Madium",
  "Matcha",
  "Matrix Hub",
  "Nezur",
  "Nihon",
  "Nucleus",
  "Opiumware",
  "Oxygen",
  "Photon",
  "Potassium",
  "RbxCli",
  "Ronix",
  "Script-Ware",
  "Seliware",
  "Serotonin",
  "Severe",
  "SirHurt",
  "Solara",
  "Swift",
  "Synapse",
  "Trigon",
  "Vega",
  "Velocity",
  "Volcano",
  "Volt",
  "Wave",
  "Xeno",
  "Zenith",
  "autoexec",
  "browser_history_domain",
  "exploit_api_surface",
  "handle_enumeration",
  "hyperion_bypass",
  "known_install_path",
  "live_external_handle",
  "live_injected_module",
  "live_memory_region",
  "live_process",
  "manual map",
  "roblox_autoexec",
  "roblox_protocol_registry",
  "threadless",
  "executor",
  "inject",
  "script hub",
  "sUNC",
  "UNC",
];

export function textMatchesSearch(text, query) {
  const q = String(query || "").trim().toLowerCase();
  if (!q) return true;
  return String(text || "").toLowerCase().includes(q);
}
